version: '3'

services:
    clickhouse-zookeeper-01:
        image: zookeeper
        ports:
            - "2181:2181"
            - "2182:2182"
        container_name: clickhouse-zookeeper-01
        hostname: clickhouse-zookeeper-01

    clickhouse-zookeeper-02:
        image: zookeeper
        ports:
            - "2281:2181"
            - "2282:2182"
        container_name: clickhouse-zookeeper-02
        hostname: clickhouse-zookeeper-02

    # cluster_old
    clickhouse-01:
        image: altinity/clickhouse-server:22.8.15.25.altinitystable
        hostname: clickhouse-01
        container_name: clickhouse-01
        ports:
            - 9001:9000
            - 8221:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika_new.xml:/etc/clickhouse-server/metrika.xml
                - ./config/storage.xml:/etc/clickhouse-server/storage.xml
                - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-01:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"

    # cluster_old
    clickhouse-01-replica:
        image: altinity/clickhouse-server:22.8.15.25.altinitystable
        hostname: clickhouse-01-replica
        container_name: clickhouse-01-replica
        ports:
            - 9051:9000
            - 8251:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika_new.xml:/etc/clickhouse-server/metrika.xml
                - ./config/storage.xml:/etc/clickhouse-server/storage.xml
                - ./config/macros/macros-01-replica.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-01:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"

networks:
    default:
        name: sentry
