version: '3'

services:
    zookeeper-01:
        networks:
          - zk
          - zk2
        image: zookeeper
        restart: always
        ports:
            - "2281:2181"
            - "2282:2182"
        container_name: zookeeper-01
        hostname: zookeeper-01
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper-01:2888:3888;2181 server.2=zookeeper-02:2888:3888;2181 server.3=zookeeper-03:2888:3888;2181
            ZOO_4LW_COMMANDS_WHITELIST: srvr,stat,mntr
            ZOO_CFG_EXTRA: zookeeper_current_node_hostname=0.0.0.0


    zookeeper-02:
        networks:
          - zk
          - zk2
        image: zookeeper
        restart: always
        ports:
            - "2283:2181"
            - "2284:2182"
        container_name: zookeeper-02
        hostname: zookeeper-02
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zookeeper-01:2888:3888;2181 server.2=zookeeper-02:2888:3888;2181 server.3=zookeeper-03:2888:3888;2181 
            ZOO_4LW_COMMANDS_WHITELIST: srvr,stat,mntr
            ZOO_CFG_EXTRA: zookeeper_current_node_hostname=0.0.0.0

    zookeeper-03:
        networks:
          - zk
          - zk2
        image: zookeeper
        restart: always
        ports:
            - "2285:2181"
            - "2286:2182"
        container_name: zookeeper-03
        hostname: zookeeper-03
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zookeeper-01:2888:3888;2181 server.2=zookeeper-02:2888:3888;2181 server.3=zookeeper-03:2888:3888;2181 
            ZOO_4LW_COMMANDS_WHITELIST: srvr,stat,mntr
            ZOO_CFG_EXTRA: zookeeper_current_node_hostname=0.0.0.0

    # cluster_new
    storage-01:
        networks:
          - zk2
          - storage
          - sta
        #   - querya
        image: clickhouse/clickhouse-server:21.8
        hostname: storage-01
        container_name: storage-01
        ports:
            - 9013:9000
            - 8013:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/storage.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/storage-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "zookeeper-01"
            - "zookeeper-02"
            - "zookeeper-03"

    # cluster_new
    storage-02:
        networks:
          - zk
          - storage
          - stb
        #   - queryb
        image: clickhouse/clickhouse-server:21.8
        hostname: storage-02
        container_name: storage-02
        ports:
            - 9023:9000
            - 8023:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/storage.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/storage-02.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "zookeeper-01"
            - "zookeeper-02"
            - "zookeeper-03"

    storage-03:
        networks:
          - zk
          - storage
          - stc
        #   - queryc
        image: clickhouse/clickhouse-server:21.8
        hostname: storage-03
        container_name: storage-03
        ports:
            - 9033:9000
            - 8033:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/storage.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/storage-03.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "zookeeper-01"
            - "zookeeper-02"
            - "zookeeper-03"

    query-1:
        networks:
          - sta
          - stb
          - stc
        #   - query
        image: clickhouse/clickhouse-server:21.8
        hostname: query-01
        container_name: query-01
        ports:
            - 9113:9000
            - 8123:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/query.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/query-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-06:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "zookeeper-01"
            - "zookeeper-02"
            - "zookeeper-03"
            - 'storage-01'
            - 'storage-02'
            - 'storage-03'
networks:
    sta:
     name: sta
    stb:
     name: stb
    stc:
     name: stc
    storage:
     name: storage
    zk:
     name: zk
    zk2:
     name: zk2
      