version: '3'

services:
    clickhouse-zookeeper-01:
        image: zookeeper
        ports:
            - "2181:2181"
            - "2182:2182"
        container_name: clickhouse-zookeeper-01
        hostname: clickhouse-zookeeper-01

    # cluster_new
    cluster-one-sh-01:
        image: clickhouse/clickhouse-server:21.8
        hostname: cluster-one-sh-01
        container_name: cluster-one-sh-01
        ports:
            - 9003:9000
            - 8223:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika_new.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"

    # cluster_new
    cluster-one-sh-query:
        image: clickhouse/clickhouse-server:21.8
        hostname: cluster-one-sh-query
        container_name: cluster-one-sh-query
        ports:
            - 9004:9000
            - 8224:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika_new.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-query.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"

networks:
    default:
        name: sentry
