version: '3'

services:
    clickhouse-zookeeper-01:
        image: zookeeper
        ports:
            - "2181:2181"
            - "2182:2182"
        container_name: clickhouse-zookeeper-01
        hostname: clickhouse-zookeeper-01

    # cluster_old
    clickhouse-01:
        image: clickhouse/clickhouse-server:22.8
        hostname: clickhouse-01
        container_name: clickhouse-01
        ports:
            - 9051:9000
            - 8251:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-01:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"

    # cluster_old
    clickhouse-01-replica:
        image: clickhouse/clickhouse-server:22.8
        hostname: clickhouse-01-replica
        container_name: clickhouse-01-replica
        ports:
            - 9052:9000
            - 8252:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-01-replica.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-02:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"

    # cluster_old
    clickhouse-02:
        image: clickhouse/clickhouse-server:22.8
        hostname: clickhouse-02
        container_name: clickhouse-02
        ports:
            - 9053:9000
            - 8253:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-02.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"


    # migrations cluster
    clickhouse-migrations-01:
        image: clickhouse/clickhouse-server:22.8
        hostname: clickhouse-migrations-01
        container_name: clickhouse-migrations-01
        ports:
            - 9054:9000
            - 8254:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-migrations-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-05:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144

    # query_old
    query-old:
        image: clickhouse/clickhouse-server:22.8
        hostname: query-old
        container_name: query-old
        ports:
            - 9005:9000
            - 8225:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                # - ./data/server-06:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        
    custom:
        build:
            context: ~/snuba
            dockerfile: Dockerfile
            args:
                - SHOULD_BUILD_RUST=false
        ports:
            - "1218:1218"
        environment:
            SNUBA_SETTINGS: test_distributed_migrations
            CLICKHOUSE_HOST_MIGRATIONS: "query-old"
            CLICKHOUSE_DATABASE: "default"
            REDIS_HOST: "172.28.0.1"
    redis:
        image: redis:5.0-alpine
        ports:
            - "6379:6379"


    # clickhouse-02-replica:
    #     image: yandex/clickhouse-server:20.7
    #     hostname: clickhouse-02-replica
    #     container_name: clickhouse-02-replica
    #     ports:
    #         - 9055:9000
    #         - 8255:8123
    #     volumes:
    #             - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
    #             - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
    #             - ./config/macros/macros-02-replica.xml:/etc/clickhouse-server/config.d/macros.xml
    #             - ./config/users.xml:/etc/clickhouse-server/users.xml
    #             # - ./data/server-04:/var/lib/clickhouse
    #     ulimits:
    #         nofile:
    #             soft: 262144
    #             hard: 262144
    #     depends_on:
    #         - "clickhouse-zookeeper-01"

networks:
    default:
        name: clickhouse-setup-network
        external: true
