version: '3'

services:
    clickhouse-zookeeper-01:
        image: zookeeper
        ports:
            - "2181:2181"
            - "2182:2182"
        container_name: clickhouse-zookeeper-01
        hostname: clickhouse-zookeeper-01
        platform: linux/arm64/v8

    # 21.8 node
    clickhouse-01:
        image: altinity/clickhouse-server:22.8.15.25.altinitystable
        hostname: clickhouse-01
        platform: linux/arm64/v8
        container_name: clickhouse-01
        ports:
            - 9051:9000
            - 8251:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                - ./data/server-01:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"

    # 22.8 node
    clickhouse-01-replica:
        image: altinity/clickhouse-server:21.8.12.1.testingarm
        hostname: clickhouse-01-replica
        platform: linux/arm64
        container_name: clickhouse-01-replica
        ports:
            - 9052:9000
            - 8252:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/macros/macros-01-replica.xml:/etc/clickhouse-server/config.d/macros.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                - ./data/server-02:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper-01"


    query:
        image: altinity/clickhouse-server:21.8.12.1.testingarm
        hostname: query
        platform: linux/arm64
        container_name: query
        ports:
            - 9005:9000
            - 8225:8123
        volumes:
                - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
                - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
                - ./config/users.xml:/etc/clickhouse-server/users.xml
                - ./data/server-03:/var/lib/clickhouse
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        
    # custom:
    #     build:
    #         context: ~/snuba
    #         dockerfile: Dockerfile
    #         args:
    #             - SHOULD_BUILD_RUST=false
    #     ports:
    #         - "1218:1218"
    #     environment:
    #         SNUBA_SETTINGS: test_distributed_migrations
    #         CLICKHOUSE_HOST_MIGRATIONS: "query-old"
    #         CLICKHOUSE_DATABASE: "default"
    #         REDIS_HOST: "172.28.0.1"
    # redis:
    #     image: redis:5.0-alpine
    #     ports:
    #         - "6379:6379"


    # clickhouse-02-replica:
    #     image: yandex/clickhouse-server:20.7
    #     hostname: clickhouse-02-replica
    #     container_name: clickhouse-02-replica
    #     ports:
    #         - 9055:9000
    #         - 8255:8123
    #     volumes:
    #             - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
    #             - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
    #             - ./config/macros/macros-02-replica.xml:/etc/clickhouse-server/config.d/macros.xml
    #             - ./config/users.xml:/etc/clickhouse-server/users.xml
    #             # - ./data/server-04:/var/lib/clickhouse
    #     ulimits:
    #         nofile:
    #             soft: 262144
    #             hard: 262144
    #     depends_on:
    #         - "clickhouse-zookeeper-01"

# networks:
#     default:
#         name: clickhouse-setup-network
#         external: true
